---

kind: pipeline
name: default

platform:
  os: linux
  arch: amd64

workspace:
  base: /go
  path: src/github.com/factorysh/gyumao

steps:
  - name: test
    pull: default
    image: golang
    commands:
      - go get -u github.com/golang/dep/cmd/dep
      - dep ensure
      - make tests