---

kind: pipeline
name: default

platform:
  os: linux
  arch: amd64

workspace:
  base: /go
  path: src/github.com/factorysh/gyumao

steps:
  - name: test
    pull: default
    image: golang
    commands:
      - go get -u github.com/golang/dep/cmd/dep
      - dep ensure
      - >
          go test -v -cover
          github.com/factorysh/gyumao/deadman
          github.com/factorysh/gyumao/evaluator
          github.com/factorysh/gyumao/plugin
          github.com/factorysh/gyumao/probes
          github.com/factorysh/gyumao/point
          github.com/factorysh/gyumao/rule
          github.com/factorysh/gyumao/timeline
      - go build -o bin/gyumao