
[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "github.com/influxdata/influxdb"
  version = "1.7.6"

[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "^1.4.1"