
[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "github.com/influxdata/influxdb"
  version = "~1.7.6"

[[constraint]]
  name = "github.com/antonmedv/expr"
  branch = "master"

[[constraint]]
  name = "github.com/willf/bitset"
  version = "^1.1.10"

[[constraint]]
  name = "github.com/influxdata/telegraf"
  version = "~1.11.3"

[[constraint]]
  name = "github.com/hashicorp/go-plugin"
  version = "^1.0.1"

[[constraint]]
  name = "gopkg.in/yaml.v2"
  version = "^2.2.2"

[[constraint]]
  name = "github.com/armon/go-radix"
  version = "1.0.0"

[[constraint]]
  name = "github.com/onrik/logrus"
  branch = "master"